web:
  image: thedillonb/codehub-push:1.0.1
  command: node /app/bin/www
  ports:
    - "127.0.0.1:9666:3000"
  volumes:
    - "./database.db:/app/database.db"

feedback:
  image: thedillonb/codehub-push:1.0.1
  command: node /app/bin/feedback
  volumes:
    - "./database.db:/app/database.db"
    - "./certs:/app/certs"
  environment:
    NODE_ENV: production

background:
  image: thedillonb/codehub-push:1.0.1
  command: node /app/bin/background
  volumes:
    - "./database.db:/app/database.db"
    - "./certs:/app/certs"
  environment:
    NODE_ENV: production
